ShopTARge24/ShopTARge24/Models/RealEstates/RealEstateCreateUpdateViewModel.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARge24.Models.Spaceships;

namespace ShopTARge24.Models.RealEstates
{
    public class RealEstateCreateUpdateViewModel
    {
        public Guid? Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }

        public List<IFormFile> Files { get; set; }
        public List<ImageViewModel> Images { get; set; }
            = new List<ImageViewModel>();
        public object ImageViewModels { get; internal set; }
    }
}

ShopTARge24/ShopTARge24/Models/RealEstates/RealEstatesIndexViewModel.cs
using Microsoft.AspNetCore.Mvc;

namespace ShopTARge24.Models.RealEstates
{
    public class RealEstatesIndexViewModel
    {
        public Guid Id { get; set; }
        public double? Area { get; set; }
        public string? Location { get; set; }
        public int? RoomNumber { get; set; }
        public string? BuildingType { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ModifiedAt { get; set; }
    }
}

ShopTARge24/ShopTARge24/Controllers/RealEstatesController.cs
using System.Buffers.Text;
using System.Xml;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.Identity.Client;
using ShopTARge24.Core.Domain;
using ShopTARge24.Core.Dto;
using ShopTARge24.Core.ServiceInterface;
using ShopTARge24.Data;
using ShopTARge24.Models.RealEstates;
using ShopTARge24.Models.Spaceships;


namespace ShopTARge24.Controllers
{
    public class RealEstatesController : Controller
    {
        private readonly ShopTARge24Context _context;
        private readonly IRealEstateServices _realestateServices;
        private readonly IFileServices _fileServices;

        public RealEstatesController
            (
                ShopTARge24Context context,
                IRealEstateServices realEstateServices,
                IFileServices fileServices
            )
        {
            _context = context;
            _realestateServices = realEstateServices;
            _fileServices = fileServices;
        }


        public IActionResult Index()
        {
            var result = _context.RealEstates
                .Select(x => new RealEstatesIndexViewModel
                {
                    Id = x.Id,
                    Area = x.Area,
                    Location = x.Location,
                    RoomNumber = x.RoomNumber,
                    BuildingType = x.BuildingType,
                    CreatedAt = x.CreatedAt,
                    ModifiedAt = x.ModifiedAt
                })
        .ToList();
        return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            RealEstateCreateUpdateViewModel result = new();

            return View("CreateUpdate", result);
        }


        [HttpPost]
        public async Task<IActionResult> Create(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = Guid.NewGuid(),
                Area = vm.Area,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                Image = vm.Images
                    .Select(x => new FileToDatabaseDto
                    {
                        Id = x.ImageId,
                        ImageData = x.ImageData,
                        ImageTitle = x.ImageTitle,
                        RealEstateId = x.RealEstateId,
                    }).ToArray(),
                FileToApiDtos = vm.Images
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.Filepath,
                        SpaceshipId = x.SpaceshipId
                    }).ToArray()
            };

            

            var result = await _realestateServices.Create(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var realestate = await _realestateServices.DetailAsync(id);

            if (realestate == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageViewModel
                {
                    Filepath = y.ExistingFilePath,
                    ImageId = y.Id,
                    RealEstateId = y.RealEstateId,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateCreateUpdateViewModel();

            vm.Id = realestate.Id;
            vm.Area = realestate.Area;
            vm.Location = realestate.Location;
            vm.RoomNumber = realestate.RoomNumber;
            vm.BuildingType = realestate.BuildingType;
            vm.CreatedAt = realestate.CreatedAt;
            vm.ModifiedAt = realestate.ModifiedAt;
            vm.Images.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RealEstateCreateUpdateViewModel vm)
        {
            var dto = new RealEstateDto()
            {
                Id = Guid.NewGuid(),
                Area = vm.Area,
                Location = vm.Location,
                RoomNumber = vm.RoomNumber,
                BuildingType = vm.BuildingType,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files,
                FileToApiDtos = vm.Images
                    .Select(x => new FileToApiDto
                    {
                        Id = x.ImageId,
                        ExistingFilePath = x.Filepath,
                        SpaceshipId = x.SpaceshipId
                    }).ToArray()
            };

            var result = await _realestateServices.Update(dto);

            if (result == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var realEstate = await _realestateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            //Piltide nägemise funktsioon
            var images = await _context.FileToApis
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageViewModel
                {
                    Filepath = y.ExistingFilePath,
                    ImageId = y.Id,
                    RealEstateId = y.RealEstateId,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDeleteViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.ImageViewModels.AddRange(images);

            return View(vm);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var realEstate = await _realestateServices.Delete(id);

            if (realEstate == null)
            {
                return RedirectToAction(nameof(Index));
            }


            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var realEstate = await _realestateServices.DetailAsync(id);

            if (realEstate == null)
            {
                return NotFound();
            }

            var images = await _context.FileToApis
                .Where(x => x.RealEstateId == id)
                .Select(y => new ImageViewModel
                {
                    Filepath = y.ExistingFilePath,
                    Id = y.Id,
                    RealEstateId = y.RealEstateId,
                    ImageData = y.ImageData,
                    ImageTitle = y.ImageTitle,
                    Image = string.Format("data:image/gif;base64,{0}", Convert.ToBase64String(y.ImageData))
                }).ToArrayAsync();

            var vm = new RealEstateDetailsViewModel();

            vm.Id = realEstate.Id;
            vm.Area = realEstate.Area;
            vm.Location = realEstate.Location;
            vm.RoomNumber = realEstate.RoomNumber;
            vm.CreatedAt = realEstate.CreatedAt;
            vm.ModifiedAt = realEstate.ModifiedAt;
            vm.Image.AddRange(images);

            return View(vm);
        }

        public async Task<IActionResult> RemoveImage(ImageViewModel vm)
        {
            //Tuleb ühendada dto ja vm (viewmodel), Id peab saama edastatud andmebaasi
            var dto = new FileToApiDto()
            {
                Id = vm.ImageId
            };

            //Kutsu välja vastav serviceclass meetod
            var image = await _fileServices.RemoveImageFromApi(dto);

            //Kui on null siis vii Index vaatesse
            if (image == null)
            {
                return RedirectToAction(nameof(Index));
            }

            return RedirectToAction(nameof(Index));
        }
    }

}

ShopTARge24/ShopTARge24/Controllers/SpaceshipsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ShopTARge24.Core.Domain;
using ShopTARge24.Core.Dto;
using ShopTARge24.Core.ServiceInterface;
using ShopTARge24.Data;
using ShopTARge24.Models.Spaceships;

namespace ShopTARge24.Controllers
{
    public class SpaceshipsController : Controller
    {
        private readonly ShopTARge24Context _context;
        private readonly ISpaceshipServices _spaceshipServices;
        private readonly IFileServices _fileServices;

        public SpaceshipsController(
            ShopTARge24Context context,
            ISpaceshipServices spaceshipServices,
            IFileServices fileServices)
        {
            _context = context;
            _spaceshipServices = spaceshipServices;
            _fileServices = fileServices;
        }

        public IActionResult Index()
        {
            var result = _context.Spaceships
                .Select(x => new SpaceshipIndexViewModel
                {
                    Id = x.Id,
                    Name = x.Name,
                    Classification = x.Classification,
                    BuiltDate = x.BuiltDate,
                    Crew = x.Crew,
                });
            return View(result);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View("CreateUpdate", new SpaceshipCreateUpdateViewModel());
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto
            {
                Id = vm.Id,
                Name = vm.Name,
                Classification = vm.Classification,
                BuiltDate = vm.BuiltDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files
            };

            var created = await _spaceshipServices.Create(dto);

            if (vm.Files != null && vm.Files.Count > 0)
            {
                _fileServices.FilesToApi(dto, created ?? new Spaceships { Id = dto.Id });
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Details), new { id = created?.Id ?? dto.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Update(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);
            if (spaceship == null) return NotFound();

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    Filepath = y.ExistingFilePath,
                    ImageId = y.Id,
                    SpaceshipId = y.SpaceshipId,
                    ImageTitle = y.ImageTitle,
                    ImageData = y.ImageData,
                    Image = y.ImageData != null
                        ? $"data:image/jpg;base64,{Convert.ToBase64String(y.ImageData)}"
                        : null
                })
                .ToArrayAsync();

            var vm = new SpaceshipCreateUpdateViewModel
            {
                Id = spaceship.Id,
                Name = spaceship.Name,
                Classification = spaceship.Classification,
                BuiltDate = spaceship.BuiltDate,
                Crew = spaceship.Crew,
                EnginePower = spaceship.EnginePower,
                CreatedAt = spaceship.CreatedAt,
                ModifiedAt = spaceship.ModifiedAt
            };
            vm.Image.AddRange(images);

            return View("CreateUpdate", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(SpaceshipCreateUpdateViewModel vm)
        {
            var dto = new SpaceshipDto
            {
                Id = vm.Id,
                Name = vm.Name,
                Classification = vm.Classification,
                BuiltDate = vm.BuiltDate,
                Crew = vm.Crew,
                EnginePower = vm.EnginePower,
                CreatedAt = vm.CreatedAt,
                ModifiedAt = vm.ModifiedAt,
                Files = vm.Files
            };

            var updated = await _spaceshipServices.Update(dto);

            if (vm.Files != null && vm.Files.Count > 0)
            {
                _fileServices.FilesToApi(dto, updated ?? new Spaceships { Id = dto.Id });
                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Details), new { id = dto.Id });
        }

        [HttpGet]
        public async Task<IActionResult> Delete(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);
            if (spaceship == null) return NotFound();

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    Filepath = y.ExistingFilePath,
                    ImageId = y.Id,
                    SpaceshipId = y.SpaceshipId,
                    ImageTitle = y.ImageTitle,
                    ImageData = y.ImageData,
                    Image = y.ImageData != null
                        ? $"data:image/jpg;base64,{Convert.ToBase64String(y.ImageData)}"
                        : null
                })
                .ToArrayAsync();

            var vm = new SpaceshipDeleteViewModel
            {
                Id = spaceship.Id,
                Name = spaceship.Name,
                Classification = spaceship.Classification,
                BuiltDate = spaceship.BuiltDate,
                Crew = spaceship.Crew,
                EnginePower = spaceship.EnginePower,
                CreatedAt = spaceship.CreatedAt,
                ModifiedAt = spaceship.ModifiedAt
            };
            vm.ImageViewModels.AddRange(images);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmation(Guid id)
        {
            var spaceship = await _spaceshipServices.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            var spaceship = await _spaceshipServices.DetailAsync(id);
            if (spaceship == null) return NotFound();

            var images = await _context.FileToApis
                .Where(x => x.SpaceshipId == id)
                .Select(y => new ImageViewModel
                {
                    Filepath = y.ExistingFilePath,
                    ImageId = y.Id,
                    SpaceshipId = y.SpaceshipId,
                    ImageTitle = y.ImageTitle,
                    ImageData = y.ImageData,
                    Image = y.ImageData != null
                        ? $"data:image/jpg;base64,{Convert.ToBase64String(y.ImageData)}"
                        : null
                })
                .ToArrayAsync();

            var vm = new SpaceshipDetailsViewModel
            {
                Id = spaceship.Id,
                Name = spaceship.Name,
                Classification = spaceship.Classification,
                BuiltDate = spaceship.BuiltDate,
                Crew = spaceship.Crew,
                EnginePower = spaceship.EnginePower,
                CreatedAt = spaceship.CreatedAt,
                ModifiedAt = spaceship.ModifiedAt
            };
            vm.Images.AddRange(images);

            return View(vm);
        }
    }
}

ShopTARge24/ShopTARge24/Views/RealEstates/CreateUpdate.cshtml
@model ShopTARge24.Models.RealEstates.RealEstateCreateUpdateViewModel

@if (Model.Id.HasValue)
{
    <h1>Update</h1>
}
else
{
    <h1>Create</h1>
}

<div>
    <form method="post" enctype="multipart/form-data">
        <input asp-for="Id" type="hidden" />
        <input asp-for="CreatedAt" type="hidden" />
        <input asp-for="ModifiedAt" type="hidden" />

        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Area" class="form-control" />
                <span asp-validation-for="Area" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="Location" class="form-control" />
                <span asp-validation-for="Location" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="RoomNumber" class="form-control" />
                <span asp-validation-for="RoomNumber" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-10">
                <input asp-for="BuildingType" class="form-control" />
                <span asp-validation-for="BuildingType" class="text-danger"></span>
            </div>
        </div>

        <div class="form-group row">
            <label asp-for="Files" class="col-sm-2 col-form-label"></label>
            <div class="col-sm-5">
                <div class="custom-file">
                    <input asp-for="Files" multiple type="file" class="form-control" />
                </div>
            </div>
        </div>

        <div>
            @foreach (var images in Model.Images)
            {
                <partial name="_Images" model="images"/>    
            }
        </div>

        @if (Model.Images != null && Model.Images.Any())
        {
            foreach (var image in Model.Images)
            {
                <partial name="_Images" model="image" />
            }
        }

        <div class="form-group row">
            <div class="col-sm-10 offset-sm-2">
                @if (Model.Id.HasValue)
                {
                    <input asp-action="Update" asp-controller="RealEstates" type="submit" class="btn btn-success" value="Update" />
                }
                else
                {
                    <input asp-action="Create" asp-controller="RealEstates" type="submit" class="btn btn-success" value="Create" />
                }

                <a asp-action="Index" asp-controller="RealEstates" class="btn btn-secondary">Back</a>
            </div>
        </div>
    </form>
</div>

ShopTARge24/ShopTARge24/Views/RealEstates/Delete.cshtml
@model ShopTARge24.Models.RealEstates.RealEstateDeleteViewModel

<h1>Delete</h1>

<div>
    <h4>RealEstates</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Area)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Location)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    @foreach (var images in Model.ImageViewModels)
    {
        <partial name="_Images" model="images" />
    }

    <hr />
    <form asp-action="DeleteConfirmation">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="RealEstates" class="btn btn-success">Back</a>
    </form>

</div>

ShopTARge24/ShopTARge24/Views/RealEstates/Details.cshtml
@model ShopTARge24.Models.RealEstates.RealEstateDetailsViewModel

<h1>Details</h1>

<div>
    <h4>RealEstates</h4>
    <hr />
    <dl class="row">
        <div class="form-group row">
            <label asp-for="Id" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Id)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Area" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Area)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="Location" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.Location)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="RoomNumber" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.RoomNumber)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="BuildingType" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.BuildingType)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="CreatedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.CreatedAt)
        </div>
    </dl>

    <dl class="row">
        <div class="form-group row">
            <label asp-for="ModifiedAt" class="col-sm-2 col-form-label"></label>
            @Html.DisplayFor(model => model.ModifiedAt)
        </div>
    </dl>

    @foreach (var images in Model.Image)
    {
        <partial name="_Images" model="images" />
    }

    <hr />
    <a asp-action="Index" asp-controller="RealEstates" class="btn btn-danger">Back</a>
</div>

ShopTARge24/ShopTARge24/Views/RealEstates/Index.cshtml
@model IEnumerable<ShopTARge24.Models.RealEstates.RealEstatesIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="RealEstates" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    RealEstates
</div>
<form method="get">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Area</th>
                <th scope="col">Location</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">BuildingType</th>
                <th scope="col">CreatedAt</th>
                <th scope="col">ModifiedAt</th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var realestate in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@realestate.Id</td>
                    <td>@realestate.Area</td>
                    <td>@realestate.Location</td>
                    <td>@realestate.RoomNumber</td>
                    <td>@realestate.BuildingType</td>
                    <td>@realestate.CreatedAt</td>
                    <td>@realestate.ModifiedAt</td>
                    <td class="d-flex gap-2">
                        <a asp-action="details" asp-controller="RealEstates" asp-route-id="@realestate.Id" class="btn btn-info">Details</a>
                        <a asp-action="update" asp-controller="RealEstates" asp-route-id="@realestate.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="RealEstates" asp-route-id="@realestate.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARge24/ShopTARge24/Views/RealEstates/RealEstate.cshtml
@model IEnumerable<ShopTARge24.Models.RealEstates.RealEstatesIndexViewModel>

@{
    int rowNumber = 1;
}

<div>
    <a asp-action="create" asp-controller="Spaceships" type="submit" class="btn btn-primary">Create</a>
</div>

<div class="h1">
    RealEstates
</div>
<form method="get">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Id</th>
                <th scope="col">Area</th>
                <th scope="col">Location</th>
                <th scope="col">RoomNumber</th>
                <th scope="col">CreatedAt</th>
                <th scope="col">ModifiedAt</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var realestate in Model)
            {
                <tr>
                    <td>@rowNumber</td>
                    <td>@realestate.Id</td>
                    <td>@realestate.Area</td>
                    <td>@realestate.Location</td>
                    <td>@realestate.RoomNumber</td>
                    <td>@realestate.BuildingType</td>
                    <td>@realestate.CreatedAt</td>
                    <td>@realestate.ModifiedAt</td>
                    <td>
                        <a asp-action="details" asp-controller="RealEstates" asp-route-id="@realestate.Id" class="btn btn-primary">Details</a>
                        <a asp-action="update" asp-controller="RealEstates" asp-route-id="@realestate.Id" class="btn btn-primary">Update</a>
                        <a asp-action="delete" asp-controller="RealEstates" asp-route-id="@realestate.Id" class="btn btn-outline-danger">Delete</a>
                    </td>
                </tr>
                rowNumber += 1;
            }
        </tbody>
    </table>
</form>

ShopTARge24/ShopTARge24/Views/RealEstates/_Images.cshtml
@model ShopTARge24.Models.Spaceships.ImageViewModel

@{
    var photoPaths = "~/multipleFileUpload/" + (Model.Filepath ?? "noimage.jpg");
}

<div class="form-group row col-sm-4 offset-2">
    <div>@Model.ImageTitle</div>
    <img class="card-image-top" src="@Model.Image" asp-append-version="true" />
</div>