ShopTARge24/ShopTARge24/Models/ChuckNorris/ChuckNorrisModel.cs
namespace ShopTARge24.Models.ChuckNorris
{
    public class ChuckNorrisModel
    {
        public string[] Categories { get; set; }
        public string Created_at { get; set; }
        public string Icon_url { get; set; }
        public string Id { get; set; }
        public string Updated_at { get; set; }
        public string Url { get; set; }
        public string Value { get; set; }
    }
}

ShopTARge24/ShopTARge24/Controllers/ChuckNorrisController.cs
using Microsoft.AspNetCore.Mvc;
using ShopTARge24.Models.ChuckNorris;
using System.Net;
using System.Text.Json;

namespace ShopTARge24.Controllers
{
    public class ChuckNorrisController : Controller
    {
        public IActionResult Index()
        {
            ChuckNorrisModel Joke = GetRandomJoke();
            return View(Joke);
        }

        private ChuckNorrisModel GetRandomJoke()
        {
            string url = "https://api.chucknorris.io/jokes/random";
            using (WebClient client = new WebClient())
            {
                string json = client.DownloadString(url);
                var joke = JsonSerializer.Deserialize<ChuckNorrisModel>(json, new JsonSerializerOptions
                {
                    PropertyNameCaseInsensitive = true
                });

                return joke;
            }
        }
    }
}

ShopTARge24/ShopTARge24/Views/ChuckNorris/Index.cshtml
@model ShopTARge24.Models.ChuckNorris.ChuckNorrisModel

<h1>Joke</h1>

<div class="container mt-4">
    <h2>Random Joke from Chuck</h2>
    <img src="https://i.gifer.com/2Xx.gif" alt="Chuck Norris" width="100" />
    <p class="lead">@Model.Value</p>

    <a class="bt btn-primary" asp-controller="ChuckNorris" asp-action="Index">Another?</a>
</div>